import type { ProviderDefinition } from '@srouter/types';

export const PROVIDER_CATALOG: ProviderDefinition[] = [
    // --- 1. Custom Providers (OpenAI/Anthropic Compatible) ---
    {
        id: 'gorouter',
        name: 'gorouter',
        category: 'custom',
        protocol: 'openai',
        description: 'Custom GoRouter OpenAI Compatible Proxy',
        requiresApiKey: true,
        supportsCustomUrl: true,
        status: { state: 'connected', connectedCount: 1 },
        models: [
            { id: 'gorouter/claude-3-5-sonnet', object: 'model', created: 1700000000, owned_by: 'gorouter' },
            { id: 'gorouter/gpt-4o', object: 'model', created: 1700000000, owned_by: 'gorouter' },
        ],
    },
    {
        id: 'interx',
        name: 'Interx',
        category: 'custom',
        protocol: 'openai',
        description: 'Interx API Gateway',
        requiresApiKey: true,
        supportsCustomUrl: true,
        status: { state: 'connected', connectedCount: 1 },
        models: [{ id: 'interx/default-chat', object: 'model', created: 1700000000, owned_by: 'interx' }],
    },
    {
        id: 'bluesminds',
        name: 'Bluesminds',
        category: 'custom',
        protocol: 'openai',
        description: 'Bluesminds Custom AI Node',
        requiresApiKey: true,
        supportsCustomUrl: true,
        status: { state: 'connected', connectedCount: 1 },
        models: [{ id: 'bluesminds/fast-llm', object: 'model', created: 1700000000, owned_by: 'bluesminds' }],
    },
    {
        id: 'neosantara',
        name: 'Neosantara',
        category: 'custom',
        protocol: 'openai',
        description: 'Neosantara Regional AI Proxy',
        requiresApiKey: true,
        supportsCustomUrl: true,
        status: { state: 'connected', connectedCount: 1 },
        models: [{ id: 'neosantara/llama-3.3-70b', object: 'model', created: 1700000000, owned_by: 'neosantara' }],
    },
    {
        id: 'agentrouter',
        name: 'AgentRouter',
        category: 'custom',
        protocol: 'anthropic',
        description: 'AgentRouter Anthropic Protocol Proxy',
        requiresApiKey: true,
        supportsCustomUrl: true,
        status: { state: 'connected', connectedCount: 1 },
        models: [{ id: 'agentrouter/claude-3-5-haiku', object: 'model', created: 1700000000, owned_by: 'agentrouter' }],
    },

    // --- 2. OAuth Providers ---
    {
        id: 'claude_code',
        name: 'Claude Code',
        category: 'oauth',
        protocol: 'anthropic',
        description: 'Anthropic Claude Code CLI authentication',
        requiresApiKey: false,
        requiresOAuth: true,
        status: { state: 'no_connections' },
        models: [{ id: 'claude-code/claude-3-7-sonnet', object: 'model', created: 1700000000, owned_by: 'claude-code' }],
    },
    {
        id: 'antigravity',
        name: 'Antigravity',
        category: 'oauth',
        protocol: 'openai',
        description: 'Google Antigravity AI Agent Auth',
        requiresApiKey: false,
        requiresOAuth: true,
        status: { state: 'connected', connectedCount: 2 },
        models: [{ id: 'antigravity/gemini-3.6-flash', object: 'model', created: 1700000000, owned_by: 'antigravity' }],
    },
    {
        id: 'openai_codex',
        name: 'OpenAI Codex',
        category: 'oauth',
        protocol: 'openai',
        description: 'OpenAI Codex OAuth login',
        requiresApiKey: false,
        requiresOAuth: true,
        status: { state: 'no_connections' },
        models: [{ id: 'codex/gpt-4o-code', object: 'model', created: 1700000000, owned_by: 'openai' }],
    },
    {
        id: 'qoder',
        name: 'Qoder',
        category: 'oauth',
        protocol: 'openai',
        description: 'Qoder Developer Auth',
        requiresApiKey: false,
        requiresOAuth: true,
        status: { state: 'no_connections' },
        models: [{ id: 'qoder/coder-v1', object: 'model', created: 1700000000, owned_by: 'qoder' }],
    },
    {
        id: 'github_copilot',
        name: 'GitHub Copilot',
        category: 'oauth',
        protocol: 'openai',
        description: 'GitHub Copilot OAuth token integration',
        requiresApiKey: false,
        requiresOAuth: true,
        status: { state: 'no_connections' },
        models: [
            { id: 'copilot/gpt-4o', object: 'model', created: 1700000000, owned_by: 'github' },
            { id: 'copilot/claude-3.5-sonnet', object: 'model', created: 1700000000, owned_by: 'github' },
        ],
    },
    {
        id: 'cursor_ide',
        name: 'Cursor IDE',
        category: 'oauth',
        protocol: 'openai',
        description: 'Cursor IDE OAuth Session',
        requiresApiKey: false,
        requiresOAuth: true,
        status: { state: 'no_connections' },
        models: [{ id: 'cursor/claude-3.5-sonnet', object: 'model', created: 1700000000, owned_by: 'cursor' }],
    },

    // --- 3. Free Tier Providers ---
    {
        id: 'opencode_free',
        name: 'OpenCode Free',
        category: 'free_tier',
        protocol: 'openai',
        description: 'Community free LLM endpoint',
        requiresApiKey: false,
        status: { state: 'ready' },
        models: [{ id: 'opencode/deepseek-r1-free', object: 'model', created: 1700000000, owned_by: 'opencode' }],
    },
    {
        id: 'gemini_cli',
        name: 'Gemini CLI',
        category: 'free_tier',
        protocol: 'gemini',
        description: 'Free Google Gemini CLI access',
        requiresApiKey: false,
        status: { state: 'no_connections' },
        models: [{ id: 'gemini-cli/gemini-2.0-flash-exp', object: 'model', created: 1700000000, owned_by: 'google' }],
    },
    {
        id: 'openrouter',
        name: 'OpenRouter',
        category: 'free_tier',
        protocol: 'openai',
        defaultBaseUrl: 'https://openrouter.ai/api/v1',
        description: 'OpenRouter unified API router',
        requiresApiKey: true,
        status: { state: 'no_connections' },
        models: [
            { id: 'openrouter/auto', object: 'model', created: 1700000000, owned_by: 'openrouter' },
            { id: 'meta-llama/llama-3.3-70b-instruct:free', object: 'model', created: 1700000000, owned_by: 'openrouter' },
        ],
    },

    // --- 4. API Key Providers ---
    {
        id: 'anthropic',
        name: 'Anthropic',
        category: 'api_key',
        protocol: 'anthropic',
        defaultBaseUrl: 'https://api.anthropic.com/v1',
        description: 'Anthropic Claude API (Sonnet 3.7, Haiku 3.5)',
        requiresApiKey: true,
        status: { state: 'no_connections' },
        models: [
            { id: 'claude-3-7-sonnet-20250219', object: 'model', created: 1700000000, owned_by: 'anthropic' },
            { id: 'claude-3-5-sonnet-20241022', object: 'model', created: 1700000000, owned_by: 'anthropic' },
            { id: 'claude-3-5-haiku-20241022', object: 'model', created: 1700000000, owned_by: 'anthropic' },
        ],
    },
    {
        id: 'deepseek',
        name: 'DeepSeek',
        category: 'api_key',
        protocol: 'openai',
        defaultBaseUrl: 'https://api.deepseek.com/v1',
        description: 'DeepSeek V3 & DeepSeek R1 Reasoning LLMs',
        requiresApiKey: true,
        status: { state: 'no_connections' },
        models: [
            { id: 'deepseek-chat', object: 'model', created: 1700000000, owned_by: 'deepseek' },
            { id: 'deepseek-reasoner', object: 'model', created: 1700000000, owned_by: 'deepseek' },
        ],
    },
    {
        id: 'groq',
        name: 'Groq',
        category: 'api_key',
        protocol: 'openai',
        defaultBaseUrl: 'https://api.groq.com/openai/v1',
        description: 'Ultra-fast Groq LPU inference (Llama 3.3 70B, DeepSeek R1)',
        requiresApiKey: true,
        status: { state: 'no_connections' },
        models: [
            { id: 'llama-3.3-70b-versatile', object: 'model', created: 1700000000, owned_by: 'groq' },
            { id: 'deepseek-r1-distill-llama-70b', object: 'model', created: 1700000000, owned_by: 'groq' },
        ],
    },
    {
        id: 'cohere',
        name: 'Cohere',
        category: 'api_key',
        protocol: 'openai',
        defaultBaseUrl: 'https://api.cohere.com/v2',
        description: 'Cohere Command R7B and Command R+',
        requiresApiKey: true,
        status: { state: 'no_connections' },
        models: [
            { id: 'command-r-plus', object: 'model', created: 1700000000, owned_by: 'cohere' },
            { id: 'command-r', object: 'model', created: 1700000000, owned_by: 'cohere' },
        ],
    },
    {
        id: 'cerebras',
        name: 'Cerebras',
        category: 'api_key',
        protocol: 'openai',
        defaultBaseUrl: 'https://api.cerebras.ai/v1',
        description: 'Cerebras Wafer-Scale AI Inference engine',
        requiresApiKey: true,
        status: { state: 'no_connections' },
        models: [
            { id: 'llama3.1-70b', object: 'model', created: 1700000000, owned_by: 'cerebras' },
        ],
    },
    {
        id: 'azure_openai',
        name: 'Azure OpenAI',
        category: 'api_key',
        protocol: 'openai',
        description: 'Enterprise Microsoft Azure OpenAI Service',
        requiresApiKey: true,
        supportsCustomUrl: true,
        status: { state: 'no_connections' },
        models: [
            { id: 'azure/gpt-4o', object: 'model', created: 1700000000, owned_by: 'azure' },
        ],
    },
];
